### PR TITLE
Add a new item that isn't in the list

### PR DESCRIPTION
**Pull request by creedmangrum**
Hi,

This is a proposed feature. It's not quite complete yet, but I wanted to put this PR together as a request for feedback. I wanted to make sure it aligned with project interests before doing much more. I am including some screenshots of the change.

This PR adds the ability to add an item that is not in the item list. This adds and event handler so handle a new item added to the list.

Thanks,
Creed

screen shot 2017-11-29 at 3 16 37 pm

screen shot 2017-11-29 at 3 16 47 pm

screen shot 2017-11-29 at 3 16 57 pm

screen shot 2017-11-29 at 3 17 10 pm

screen shot 2017-11-29 at 3 17 19 pm

### CODE REVIEW

**Comment by toystars** [comment]
@creedmangrum thanks for this. It is really awesome. Although I never had such in mind, but thinking about it now I can see lots of possibilities with this. And yes, it is aligned with the project's interest.

I really can't wait for the complete feature so it can be merged in and pull it all together in #31. Another thing though, I am suggesting users should be able to turn the feature on and off.

Once again, thanks for this!

**Comment by creedmangrum** [comment]
@toystars Of course, I'm happy to contribute!

I'll tidy up and make it defaulted to off. Is there anything additional that you would suggest?

**Comment by creedmangrum** [comment]
also I am using this in an app I am developing so I am going to use it there while I am testing it out. So this may come more fully in a few days while working out all the kinks.

**Comment by creedmangrum** [comment]
sorry all the comments, I'm going to leave this PR up while I am working on it, but will close and squash commits later and reopen with new clean PR potentially.

**Comment by toystars** [comment]
The comments are totally alright.

As regards the style, I would suggest it follows the design of the items in the list but with an underline or something like that which easily tells the user it is an `action` item.

**Comment by toystars** [comment]
@creedmangrum how is this feature getting on? Checking by to know as it is a feature I think will be insanely useful for users. Thanks 👍

**Comment by creedmangrum** [comment]
@toystars hey! I was planning on getting it finalized tonight or in the morning tomorrow. I think I have the behavior nailed down and now I just need to make it on/off.

**Comment by toystars** [comment]
Awesome! Would also be - 254842° cooler if you update  the README to reflect the feature

**Comment by creedmangrum** [comment]
Definitely will do!

**Comment by creedmangrum** [comment]
going to be tomorrow, some other stuff came up. thanks for being patient with this one.

**Comment by creedmangrum** [comment]
Here are some updated screen shots

screen shot 2017-12-07 at 2 40 50 pm
screen shot 2017-12-07 at 2 40 39 pm

**Comment by creedmangrum** [comment]
Also, I alphabetized the prop list in the readme, I can undo that if you like. 

I updated the `react-native` in peer dependencies as there was a bug pre 0.48.2 where the `onSubmitEditing` event was not firing when `return` was clicked on native keyboards.

**Comment by toystars** [comment]
@creedmangrum big props for the enabling `return` key. Just one thing though, I think `tap` might be better instead of `click`. And about the alphabetized props in readme, that makes sense. It would make finding props easier. 💯 💯. Good one there!

**Comment by creedmangrum** [comment]
oh for sure, good call. I'll change the language to `tap`

**Comment by creedmangrum** [comment]
@toystars how's this looking? anything else you would like me to improve?

**Comment by toystars** [comment]
@creedmangrum sorry for the late response, was insanely busy. It all looks good as it is. I checked through your code and it makes total sense. Is this ready to merged or you still have cleanups to do?  will pull it in for final testing when you give me the go ahead and I will merge. Thanks man!

**Comment by creedmangrum** [comment]
No problem! No hurry on my end!

I am done cleaning up on my side!

**Comment by creedmangrum** [comment]
Hey just wondering if your testing went okay?

**Comment by toystars** [comment]
@creedmangrum gee did my testing take so long?

So just got back around testing this and it does work perfect! Thanks.

**Pull request merged**
