### PR TITLE
Add autoCorrect prop.

### PR DESCRIPTION
**Pull request by rwb392**
Adds and documents `autoCorrect` prop. Defaults to `true`, and disables the auto-correct of `TextInput` when `false`.

### CODE REVIEW

**Comment by rwb392** [comment]
Any particular reason this was closed instead of merged?

**Comment by AugustoAleGon** [comment]
@rwb392 Thanks for taking your time for make this PR. But the latest version has that in consideration we have the property `textInputProps` which you can add whatever you need including autoCorrect.

**Comment by rwb392** [comment]
@AugustoAleGon Thanks for the explanation. Good idea, I’ll do that.

**Comment by AugustoAleGon** [comment]
@rwb392 Thanks to you. If you have any other improvement, just PR and I will check it.

**Pull request closed without merging**
