### PR TITLE
Feature: listen on input change

### PR DESCRIPTION
**Pull request by donedgardo**
This adds the ability to listen on input change of the `Text Input`.
My editor also made it [prettier](https://github.com/prettier/prettier).

### CODE REVIEW

**Comment by toystars** [comment]
@donedgardo this looks good. Big props for updating README and also bumping up version number. Prettier obviously did made it a lot more sexy 💯. Just one thing though; I'd say we stick to using single quotes. It's more of a style to me though and something I am used to for quite a long time.

What do you think about this? I think there is a `prettier.singleQuote` option in `Prettier` settings that is defaulted to `false`. Maybe you can convince me and we'd leave the double quotes on :). Let's get this sorted and I'll merge at once. Thanks 👍

**Comment by donedgardo** [comment]
@toystars 

> What do you think about this? I think there is a prettier.singleQuote option in Prettier settings that is defaulted to false. Maybe you can convince me and we'd leave the double quotes on :). Let's get this sorted and I'll merge at once. Thanks 👍
 
Definitely, I will add a `dev dependency` for prettier and a `pre-commit` script to use pretier with those options.

I have no preference between, it was just the default.

Should I create  new pull request with both of the features i requested or separate pull request?

Also: 
I have a 0.4.0 version fork where i changed how `selectedItems` was stored, instead of unique ids it stores the complete object. Would this be consider breaking change?  I named it 0.4.0 might be braking change in its behavior pre`0.3.3`

What you think?

**Comment by donedgardo** [comment]
After a few tries I finally setup `precommit` hook with prettier.

**Comment by toystars** [comment]
@donedgardo this looks super awesome. Great effort! I will merge this in. 

> Also:
I have a 0.4.0 version fork where i changed how selectedItems was stored, instead of unique ids it stores the complete object. Would this be consider breaking change? I named it 0.4.0 might be braking change in its behavior pre0.3.3. What you think?

This was exactly how things worked initially as regards selected items. But I reckoned storing entire objects in `selectedItems` might be repetitive. Of course, there shouldn't be any issue with performance as all objects are passed by reference. But then, it might feel more natural to send in an array of `ids` than entire objects.

Both can be supported though i.e both array of ids or array of objects should be allowed to be passed in and internally deduce which one is passed and work some magic.

I'll also love to have #42 merged in too. Can you please update that so I can pull it in? Once again, great work 💯

**Pull request merged**
