### PR TITLE
Add a filterMethod so different filter logic can be decided as well as provide an alternate filter method

### PR DESCRIPTION
**Pull request by crcnum4**
Hi, I needed this component to use different logic on the items it was returning so I forked and added some new logic via a prop. I added it in a way that it would not effect any current users of your package as the default (not including the prop) will run the current logic you have. 

I have added the following:

New prop filterMethod. Accepts the following inputs: "full" anything else runs your default logic which I called partial this is not hard coded and can be changed.

Updated README.md to explain the new prop type by adding it to the props table. I also added to the notes section two examples of how the filters work.

Note in the new filter I tested both RegExp and indexOf() against a list of about 2000 items and from my tests it seemed indexOf returned results faster. I can submit a RegExp version if you'd prefer.

### CODE REVIEW

**Comment by AugustoAleGon** [comment]
@crcnum4 I will test it. But honestly I feel it is a great plus for the component.

**Comment by crcnum4** [comment]
Thanks, I thought it might be useful thus why I made it universal without breaking the original logic.

**Comment by AugustoAleGon** [comment]
Can you remove the expo files? I think it is not really necessary. @crcnum4

**Comment by crcnum4** [comment]
oh i included expo files? sure i can check for that

**Comment by crcnum4** [comment]
removed

**Comment by crcnum4** [comment]
Anything else I can do with this item to make it better to merge?

**Comment by crcnum4** [comment]
@AugustoAleGon 
Anything else i can do to make this pull request better?

**Comment by AugustoAleGon** [comment]
PR request approved

**Pull request merged**
